#!/usr/bin/awk -f

BEGIN {
    print "PRAGMA synchronous = OFF;"
    print "PRAGMA journal_mode = MEMORY;"
    print "BEGIN TRANSACTION;"
}

/^\/\*/ { next }
/^--/ { next }
/^SET / { next }
/^LOCK TABLES/ { next }
/^UNLOCK TABLES/ { next }
/^ALTER TABLE/ { in_alter = 1; next }
in_alter { if (/;$/) in_alter = 0; next }

/^(INSERT|REPLACE) / {
    while (match($0, /0x[0-9a-fA-F]+/)) {
        val = substr($0, RSTART+2, RLENGTH-2)
        $0 = substr($0, 1, RSTART-1) "X'" val "'" substr($0, RSTART+RLENGTH)
    }
    gsub(/\\'/, "''")
    gsub(/\\"/, "\"")
    gsub(/\\n/, "\n")
    gsub(/\\r/, "\r")
    gsub(/\\t/, "\t")
    gsub(/\\\\/, "\\")
    print
    next
}

/^CREATE.*VIEW/ {
    gsub(/ALGORITHM=[A-Za-z_]+ /, "")
    gsub(/DEFINER=[^ ]+ /, "")
    gsub(/SQL SECURITY DEFINER /, "")
    print
    in_view = 1
    if (/;$/) in_view = 0
    next
}

in_view {
    print
    if (/;$/) in_view = 0
    next
}

/^CREATE.*TRIGGER/ {
    gsub(/DEFINER=[^ ]+ /, "")
    print
    in_trigger = 1
    if (/;$/ && !/BEGIN/ && !/END/) in_trigger = 0
    next
}

in_trigger {
    print
    if (/END;/ || /END \*\//) in_trigger = 0
    next
}

/^CREATE TABLE/ {
    in_table = 1
    has_pk = 0
    if (match($0, /`[^`]+/)) {
        table_name = substr($0, RSTART+1, RLENGTH-1)
    }
    print
    prev_line = ""
    next
}

in_table {
    if (/^\) *(ENGINE|DEFAULT CHARSET|COLLATE|;)/ || /^\);/) {
        gsub(/, *$/, "", prev_line)
        if (prev_line != "") print prev_line
        print ");"
        in_table = 0
        prev_line = ""
        next
    }

    is_index = 0
    if (/^ *(KEY|UNIQUE KEY|FULLTEXT KEY|SPATIAL KEY) /) {
        if (match($0, /`[^`]+/)) idx_name = substr($0, RSTART+1, RLENGTH-1)
        if (match($0, /\([^)]+\)/)) idx_cols = substr($0, RSTART, RLENGTH)
        is_unique = (/UNIQUE/ ? "UNIQUE " : "")
        key_stmts[table_name] = key_stmts[table_name] "CREATE " is_unique "INDEX \"idx_" table_name "_" idx_name "\" ON \"" table_name "\" " idx_cols ";\n"
        is_index = 1
    }

    if (/^ *PRIMARY KEY/) {
        if (has_pk) is_index = 1
        has_pk = 1
    }

    if (is_index) {
        next
    }

    curr_line = $0
    gsub(/ COMMENT '[^']*'/, "", curr_line)
    gsub(/ CHARACTER SET [a-zA-Z0-9_]+/, "", curr_line)
    gsub(/ COLLATE [a-zA-Z0-9_]+/, "", curr_line)
    gsub(/ UNSIGNED| unsigned/, "", curr_line)
    gsub(/ ON UPDATE CURRENT_TIMESTAMP/, "", curr_line)
    
    if (curr_line ~ /AUTO_INCREMENT|auto_increment/) {
        gsub(/AUTO_INCREMENT|auto_increment/, "", curr_line)
        gsub(/[A-Za-z0-9_]*INT\([^)]+\)|[A-Za-z0-9_]*INT|[A-Za-z0-9_]*int/, "INTEGER PRIMARY KEY AUTOINCREMENT", curr_line)
        has_pk = 1
    }

    gsub(/ENUM\([^)]+\)/, "TEXT", curr_line)
    gsub(/SET\([^)]+\)/, "TEXT", curr_line)
    gsub(/` [A-Za-z0-9_]*INT\([^)]+\)/, "` INTEGER", curr_line)
    gsub(/` [A-Za-z0-9_]*INT/, "` INTEGER", curr_line)
    gsub(/` BIT\([^)]+\)/, "` INTEGER", curr_line)
    
    if (prev_line != "") print prev_line
    prev_line = curr_line
    next
}

{ print }

END {
    for (t in key_stmts) {
        printf "%s", key_stmts[t]
    }
    print "COMMIT;"
}
